# Generated by Django 5.1.1 on 2024-12-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='been_edited',
            field=models.BooleanField(default=False),
        ),
    ]
